version: '3'

services:

  dev:
    container_name: menview-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'

