FROM ubuntu:18.10

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip

COPY requirements_flask.txt .
COPY flask_api .


RUN pip3 install -r requirements_flask.txt


EXPOSE 5000

ENTRYPOINT [ "python3" ]
CMD [ "api.py" ]