FROM python:3.7

COPY requirements_flask.txt .
COPY wait.sh .
COPY flask_api .

RUN chmod +x wait.sh

RUN pip3 install -U -r requirements_flask.txt

EXPOSE 5000

CMD /wait.sh db 5432 \
  && python models.py \
  && python api.py