FROM python:3.6-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN apk add --update bash && rm -rf /var/cache/apk/*

COPY requirements_flask.txt .
COPY wait.sh .
COPY flask_api .

RUN chmod +x wait.sh


RUN pip3 install -r requirements_flask.txt


EXPOSE 5000

CMD /wait.sh db 5432 \
  && python models.py \
  && python api.py